// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum CreateSigningKeyResponse {
        case empty
        case signingKeyResponsePayload(Shared.SigningKeyResponsePayload)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func signingKeyResponsePayload() throws -> Shared.SigningKeyResponsePayload {
            guard case .signingKeyResponsePayload(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
