// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Success
    public struct CreateClipResponseBody {
        public let asset: Shared.Asset
        public let task: Operations.CreateClipTask

        /// Creates an object with the specified parameters
        ///
        ///
        public init(asset: Shared.Asset, task: Operations.CreateClipTask) {
            self.asset = asset
            self.task = task
        }
    }
}

extension Operations.CreateClipResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case asset
        case task
    }
}

