// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct DeleteAssetRequest: APIValue {
        /// ID of the asset
        public let assetId: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter assetId: ID of the asset
        ///
        public init(assetId: String) {
            self.assetId = assetId
        }
    }
}
