// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetAssetResponse {
        case empty
        case asset(Shared.Asset)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func asset() throws -> Shared.Asset {
            guard case .asset(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
