// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// The time step to aggregate viewership metrics by
    /// 
    public enum GetDataUsageQueryQueryParamTimeStep: String, Codable, APIValue {
        case hour = "hour"
        case day = "day"
    }
}
