// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetMultistreamTargetIdResponse {
        case empty
        case multistreamTarget(Shared.MultistreamTarget)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func multistreamTarget() throws -> Shared.MultistreamTarget {
            guard case .multistreamTarget(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
