// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetPlaybackIdResponse {
        case empty
        case error(Shared.Error)
        case playbackInfo(Shared.PlaybackInfo)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func error() throws -> Shared.Error {
            guard case .error(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }

        public func playbackInfo() throws -> Shared.PlaybackInfo {
            guard case .playbackInfo(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
