// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetPlaybackInfoRequest: APIValue {
        /// The ID of the playback
        public let id: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter id: The ID of the playback
        ///
        public init(id: String) {
            self.id = id
        }
    }
}
