// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetRecordedSessionsRequest: APIValue {
        /// ID of the parent stream
        public let parentId: String
        /// Flag indicating if the response should only include recorded
        /// sessions
        /// 
        public let record: Int?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter parentId: ID of the parent stream
        /// - Parameter record: Flag indicating if the response should only include recorded
        /// sessions
        /// 
        ///
        public init(parentId: String, record: Int? = nil) {
            self.parentId = parentId
            self.record = record
        }
    }
}
