// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetRoomIdUserUserIdResponse {
        case empty
        case getRoomUserResponse(Shared.GetRoomUserResponse)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func getRoomUserResponse() throws -> Shared.GetRoomUserResponse {
            guard case .getRoomUserResponse(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
