// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetRoomResponse {
        case empty
        case room(Shared.Room)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func room() throws -> Shared.Room {
            guard case .room(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
