// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetStreamRequest: APIValue {
        public let streamsonly: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(streamsonly: String? = nil) {
            self.streamsonly = streamsonly
        }
    }
}
