// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetSigningKeyResponse {
        case empty
        case signingKey(Shared.SigningKey)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func signingKey() throws -> Shared.SigningKey {
            guard case .signingKey(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
