// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetStreamIdResponse {
        case empty
        case stream(Shared.Stream)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func stream() throws -> Shared.Stream {
            guard case .stream(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
