// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetSessionResponse {
        case empty
        case session(Shared.Session)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func session() throws -> Shared.Session {
            guard case .session(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
