// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetTaskRequest: APIValue {
        /// ID of the task
        public let taskId: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter taskId: ID of the task
        ///
        public init(taskId: String) {
            self.taskId = taskId
        }
    }
}
