// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetWebhookIdRequest: APIValue {
        public let id: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: String) {
            self.id = id
        }
    }
}
