// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum CreateRoomResponse {
        case empty
        case createRoomResponse(Shared.CreateRoomResponse)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func createRoomResponse() throws -> Shared.CreateRoomResponse {
            guard case .createRoomResponse(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
