// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct PatchAccessControlSigningKeyKeyIdRequest: APIValue {
        /// ID of the signing key
        public let keyId: String
        public let requestBody: Operations.PatchAccessControlSigningKeyKeyIdRequestBody

        /// Creates an object with the specified parameters
        ///
        /// - Parameter keyId: ID of the signing key
        ///
        public init(keyId: String, requestBody: Operations.PatchAccessControlSigningKeyKeyIdRequestBody) {
            self.keyId = keyId
            self.requestBody = requestBody
        }
    }
}
