// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum PostRoomIdUserResponse {
        case empty
        case roomUserResponse(Shared.RoomUserResponse)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func roomUserResponse() throws -> Shared.RoomUserResponse {
            guard case .roomUserResponse(let value) = self else {
                throw LivepeerError.missingResponseData
            }
            return value
        }
    }
}
