// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Success
    public struct PostAssetUploadUrlResponseBody {
        public let asset: Shared.Asset
        public let task: Operations.PostAssetUploadUrlTask

        /// Creates an object with the specified parameters
        ///
        ///
        public init(asset: Shared.Asset, task: Operations.PostAssetUploadUrlTask) {
            self.asset = asset
            self.task = task
        }
    }
}

extension Operations.PostAssetUploadUrlResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case asset
        case task
    }
}

