// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct PostRoomIdEgressRequest: APIValue {
        public let id: String
        public let roomEgressPayload: Shared.RoomEgressPayload

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: String, roomEgressPayload: Shared.RoomEgressPayload) {
            self.id = id
            self.roomEgressPayload = roomEgressPayload
        }
    }
}
