// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct PostRoomIdUserRequest: APIValue {
        public let id: String
        public let roomUserPayload: Shared.RoomUserPayload

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: String, roomUserPayload: Shared.RoomUserPayload) {
            self.id = id
            self.roomUserPayload = roomUserPayload
        }
    }
}
