// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    public enum QueryParamBreakdownBy: String, Codable, APIValue {
        case deviceType = "deviceType"
        case device = "device"
        case cpu = "cpu"
        case os = "os"
        case browser = "browser"
        case browserEngine = "browserEngine"
        case continent = "continent"
        case country = "country"
        case subdivision = "subdivision"
        case timezone = "timezone"
        case viewerId = "viewerId"
    }
}
