// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct UpdateRoomUserDetailsRequest: APIValue {
        /// ID of the room
        public let id: String
        public let roomUserUpdatePayload: Shared.RoomUserUpdatePayload
        /// ID of the user
        public let userId: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter id: ID of the room
        /// - Parameter userId: ID of the user
        ///
        public init(id: String, roomUserUpdatePayload: Shared.RoomUserUpdatePayload, userId: String) {
            self.id = id
            self.roomUserUpdatePayload = roomUserUpdatePayload
            self.userId = userId
        }
    }
}
