// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct UpdateMultistreamTargetRequest: APIValue {
        /// ID of the multistream target
        public let id: String
        public let multistreamTargetPatchPayload: Shared.MultistreamTargetPatchPayload

        /// Creates an object with the specified parameters
        ///
        /// - Parameter id: ID of the multistream target
        ///
        public init(id: String, multistreamTargetPatchPayload: Shared.MultistreamTargetPatchPayload) {
            self.id = id
            self.multistreamTargetPatchPayload = multistreamTargetPatchPayload
        }
    }
}
