// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Client: LivepeerAPI {
    // MARK: - Root operations 

    // MARK: - Scoped API operations

    public var stream: StreamAPI {
        return _StreamAPI(client: self)
    }

    public var multistreamTarget: MultistreamTargetAPI {
        return _MultistreamTargetAPI(client: self)
    }

    public var webhook: WebhookAPI {
        return _WebhookAPI(client: self)
    }

    public var asset: AssetAPI {
        return _AssetAPI(client: self)
    }

    public var room: RoomAPI {
        return _RoomAPI(client: self)
    }

    public var metrics: MetricsAPI {
        return _MetricsAPI(client: self)
    }

    public var session: SessionAPI {
        return _SessionAPI(client: self)
    }

    public var accessControl: AccessControlAPI {
        return _AccessControlAPI(client: self)
    }

    public var task: TaskAPI {
        return _TaskAPI(client: self)
    }

    public var transcode: TranscodeAPI {
        return _TranscodeAPI(client: self)
    }

    public var playback: PlaybackAPI {
        return _PlaybackAPI(client: self)
    }
}

// MARK: - Request Configuration

// MARK: - Response Handlers

