// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// type of track
    public enum AssetSchemasVideoSpecType: String, Codable, APIValue {
        case video = "video"
        case audio = "audio"
    }
}
