// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum AssetSchemasSourceType: String, Codable, APIValue {
        case recording = "recording"
    }
}
