// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Attestations {
        public let address: String
        public let role: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(address: String, role: String) {
            self.address = address
            self.role = role
        }
    }
}

extension Shared.Attestations: Codable {
    enum CodingKeys: String, CodingKey {
        case address
        case role
    }
}

