// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct AttestationIpfs {
        public let dollarRef: AnyValue?
        /// Timestamp (in milliseconds) at which IPFS export task was updated
        /// 
        @DecimalSerialized
        public private(set) var updatedAt: Double?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter updatedAt: Timestamp (in milliseconds) at which IPFS export task was updated
        /// 
        ///
        public init(dollarRef: AnyValue? = nil, updatedAt: Double? = nil) {
            self.dollarRef = dollarRef
            self._updatedAt = DecimalSerialized<Double?>(wrappedValue: updatedAt)
        }
    }
}

extension Shared.AttestationIpfs: Codable {
    enum CodingKeys: String, CodingKey {
        case dollarRef = "$ref"
        case updatedAt
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.dollarRef = try container.decodeIfPresent(AnyValue.self, forKey: .dollarRef)
        self._updatedAt = try container.decodeIfPresent(DecimalSerialized<Double?>.self, forKey: .updatedAt) ?? DecimalSerialized<Double?>(wrappedValue: nil)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.dollarRef, forKey: .dollarRef)
        if self.updatedAt != nil {
            try container.encode(self._updatedAt, forKey: .updatedAt)
        }
    }
}

extension Shared.AttestationIpfs {
    var updatedAtWrapper: DecimalSerialized<Double?> {
        return _updatedAt
    }
}
