// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Force to use a specific strategy in the Catalyst pipeline. If not specified, the default strategy that Catalyst is configured for will be used. This field only available for admin users, and is only used for E2E testing.
    public enum CatalystPipelineStrategy: String, Codable, APIValue {
        case catalyst = "catalyst"
        case catalystFfmpeg = "catalyst_ffmpeg"
        case backgroundExternal = "background_external"
        case backgroundMist = "background_mist"
        case fallbackExternal = "fallback_external"
        case external = "external"
    }
}
