// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// File content to store into IPFS
    public struct Content {

        /// Creates an object
        ///
        ///
        public init() {
        }
    }
}

extension Shared.Content: Codable {
}

