// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public enum CreatorId {
        case creatorId1(Shared.CreatorId1)
    }
}

extension Shared.CreatorId: Codable {
    public init(from decoder: Decoder) throws {
        if let value = try? Shared.CreatorId1(from: decoder) {
            self = .creatorId1(value)
        } else {
            throw LivepeerError.failedToHandleResponse(.failedToDecodeResponse)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .creatorId1(let value):
            try value.encode(to: encoder)
        }
    }
}

