// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Video Metadata EIP-712 domain
    public struct Domain {
        public let name: Shared.Name
        public let version: Shared.Version

        /// Creates an object with the specified parameters
        ///
        ///
        public init(name: Shared.Name, version: Shared.Version) {
            self.name = name
            self.version = version
        }
    }
}

extension Shared.Domain: Codable {
    enum CodingKeys: String, CodingKey {
        case name
        case version
    }
}

