// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Encryption {

        /// Creates an object
        ///
        ///
        public init() {
        }
    }
}

extension Shared.Encryption: Codable {
}

