// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Error {
        public let errors: [String]

        /// Creates an object with the specified parameters
        ///
        ///
        public init(errors: [String]) {
            self.errors = errors
        }
    }
}

extension Shared.Error: Codable {
    enum CodingKeys: String, CodingKey {
        case errors
    }
}

