// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Parameters for the export task
    public struct ExportTaskParamsSchemas1 {
        /// custom URL parameters for the export task
        public let custom: Shared.Custom

        /// Creates an object with the specified parameters
        ///
        /// - Parameter custom: custom URL parameters for the export task
        ///
        public init(custom: Shared.Custom) {
            self.custom = custom
        }
    }
}

extension Shared.ExportTaskParamsSchemas1: Codable {
    enum CodingKeys: String, CodingKey {
        case custom
    }
}

