// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Output of the export task
    public struct Export {
        public let ipfs: Shared.TaskIpfs?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(ipfs: Shared.TaskIpfs? = nil) {
            self.ipfs = ipfs
        }
    }
}

extension Shared.Export: Codable {
    enum CodingKeys: String, CodingKey {
        case ipfs
    }
}

