// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public enum ExportTaskParams {
        case exportTaskParams1(Shared.ExportTaskParams1)
        case exportTaskParams2(Shared.ExportTaskParams2)
    }
}

extension Shared.ExportTaskParams: Codable {
    public init(from decoder: Decoder) throws {
        if let value = try? Shared.ExportTaskParams1(from: decoder) {
            self = .exportTaskParams1(value)
        } else if let value = try? Shared.ExportTaskParams2(from: decoder) {
            self = .exportTaskParams2(value)
        } else {
            throw LivepeerError.failedToHandleResponse(.failedToDecodeResponse)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .exportTaskParams1(let value):
            try value.encode(to: encoder)
        case .exportTaskParams2(let value):
            try value.encode(to: encoder)
        }
    }
}

