// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum Hrn: String, Codable, APIValue {
        case hlsTs = "HLS (TS)"
        case mp4 = "MP4"
        case webRtcH264 = "WebRTC (H264)"
    }
}
