// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Input video file to transcode
    public struct Input {
        /// URL of a video to transcode, accepts object-store format
        /// "s3+https"
        /// 
        public let url: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter url: URL of a video to transcode, accepts object-store format
        /// "s3+https"
        /// 
        ///
        public init(url: String? = nil) {
            self.url = url
        }
    }
}

extension Shared.Input: Codable {
    enum CodingKeys: String, CodingKey {
        case url
    }
}

