// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public enum Input {
        case transcodePayload1(Shared.TranscodePayload1)
        case transcodePayload2(Shared.TranscodePayload2)
    }
}

extension Shared.Input: Codable {
    public init(from decoder: Decoder) throws {
        if let value = try? Shared.TranscodePayload1(from: decoder) {
            self = .transcodePayload1(value)
        } else if let value = try? Shared.TranscodePayload2(from: decoder) {
            self = .transcodePayload2(value)
        } else {
            throw LivepeerError.failedToHandleResponse(.failedToDecodeResponse)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .transcodePayload1(let value):
            try value.encode(to: encoder)
        case .transcodePayload2(let value):
            try value.encode(to: encoder)
        }
    }
}

