// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Custom credentials for the Piñata service. Must have either
    /// a JWT or an API key and an API secret.
    /// 
    public struct IpfsExportParams2 {
        /// Will be added to the pinata_api_key header.
        public let apiKey: String
        /// Will be added to the pinata_secret_api_key header.
        public let apiSecret: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter apiKey: Will be added to the pinata_api_key header.
        /// - Parameter apiSecret: Will be added to the pinata_secret_api_key header.
        ///
        public init(apiKey: String, apiSecret: String) {
            self.apiKey = apiKey
            self.apiSecret = apiSecret
        }
    }
}

extension Shared.IpfsExportParams2: Codable {
    enum CodingKeys: String, CodingKey {
        case apiKey
        case apiSecret
    }
}

