// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Custom credentials for the Piñata service. Must have either
    /// a JWT or an API key and an API secret.
    /// 
    public struct IpfsExportParams2Output {
        /// Will be added to the pinata_api_key header.
        public let apiKey: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter apiKey: Will be added to the pinata_api_key header.
        ///
        public init(apiKey: String) {
            self.apiKey = apiKey
        }
    }
}

extension Shared.IpfsExportParams2Output: Codable {
    enum CodingKeys: String, CodingKey {
        case apiKey
    }
}

