// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct IpfsExportParams {
        public let dollarRef: AnyValue?
        /// Custom credentials for the Piñata service. Must have either
        /// a JWT or an API key and an API secret.
        /// 
        public let pinata: Shared.Pinata?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter pinata: Custom credentials for the Piñata service. Must have either
        /// a JWT or an API key and an API secret.
        /// 
        ///
        public init(dollarRef: AnyValue? = nil, pinata: Shared.Pinata? = nil) {
            self.dollarRef = dollarRef
            self.pinata = pinata
        }
    }
}

extension Shared.IpfsExportParams: Codable {
    enum CodingKeys: String, CodingKey {
        case dollarRef = "$ref"
        case pinata
    }
}

