// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Custom credentials for the Piñata service. Must have either
    /// a JWT or an API key and an API secret.
    /// 
    public struct IpfsExportParamsSchemas1 {
        /// Will be added to the Authorization header as a
        /// Bearer token.
        /// 
        public let jwt: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter jwt: Will be added to the Authorization header as a
        /// Bearer token.
        /// 
        ///
        public init(jwt: String) {
            self.jwt = jwt
        }
    }
}

extension Shared.IpfsExportParamsSchemas1: Codable {
    enum CodingKeys: String, CodingKey {
        case jwt
    }
}

