// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum Name: String, Codable, APIValue {
        case verifiableVideo = "Verifiable Video"
    }
}
