// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public enum NewAssetPayloadIpfs {
        case newAssetPayload1(Shared.NewAssetPayload1)
        case bool(Bool)
    }
}

extension Shared.NewAssetPayloadIpfs: Codable {
    public init(from decoder: Decoder) throws {
        if let value = try? Shared.NewAssetPayload1(from: decoder) {
            self = .newAssetPayload1(value)
        } else if let value = try? Bool(from: decoder) {
            self = .bool(value)
        } else {
            throw LivepeerError.failedToHandleResponse(.failedToDecodeResponse)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .newAssetPayload1(let value):
            try value.encode(to: encoder)
        case .bool(let value):
            try value.encode(to: encoder)
        }
    }
}

