// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Additional data to add to the NFT metadata exported to
    /// IPFS. Will be deep merged with the default metadata
    /// exported.
    /// 
    public struct NftMetadata {

        /// Creates an object
        ///
        ///
        public init() {
        }
    }
}

extension Shared.NftMetadata: Codable {
}

