// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Output of the task
    public struct Output {
        /// Output of the export task
        public let export: Shared.Export?
        /// Output of the export data task
        public let exportData: Shared.TaskExportData?
        /// Output of the upload task
        public let upload: [String: AnyValue]?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter export: Output of the export task
        /// - Parameter exportData: Output of the export data task
        /// - Parameter upload: Output of the upload task
        ///
        public init(export: Shared.Export? = nil, exportData: Shared.TaskExportData? = nil, upload: [String: AnyValue]? = nil) {
            self.export = export
            self.exportData = exportData
            self.upload = upload
        }
    }
}

extension Shared.Output: Codable {
    enum CodingKeys: String, CodingKey {
        case export
        case exportData
        case upload
    }
}

