// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum PlaybackInfoSchemasType: String, Codable, APIValue {
        case html5ApplicationVndAppleMpegurl = "html5/application/vnd.apple.mpegurl"
        case html5VideoMp4 = "html5/video/mp4"
        case html5VideoH264 = "html5/video/h264"
    }
}
