// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct PlaybackInfo {
        public let meta: Shared.Meta
        public let type: Shared.PlaybackInfoType

        /// Creates an object with the specified parameters
        ///
        ///
        public init(meta: Shared.Meta, type: Shared.PlaybackInfoType) {
            self.meta = meta
            self.type = type
        }
    }
}

extension Shared.PlaybackInfo: Codable {
    enum CodingKeys: String, CodingKey {
        case meta
        case type
    }
}

