// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum PlaybackInfoType: String, Codable, APIValue {
        case live = "live"
        case vod = "vod"
        case recording = "recording"
    }
}
