// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum PlaybackInfoSchemasMetaType: String, Codable, APIValue {
        case html5ApplicationVndAppleMpegurl = "html5/application/vnd.apple.mpegurl"
    }
}
