// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Video Metadata EIP-712 primaryType
    public enum PrimaryType: String, Codable, APIValue {
        case videoAttestation = "VideoAttestation"
    }
}
