// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Status of the recording process of this stream session.
    public enum RecordingStatus: String, Codable, APIValue {
        case waiting = "waiting"
        case ready = "ready"
        case `none` = "none"
    }
}
