// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct RoomEgressPayload {
        /// The ID of the Livepeer Stream to stream to
        public let streamId: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter streamId: The ID of the Livepeer Stream to stream to
        ///
        public init(streamId: String) {
            self.streamId = streamId
        }
    }
}

extension Shared.RoomEgressPayload: Codable {
    enum CodingKeys: String, CodingKey {
        case streamId
    }
}

