// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct RoomUserPayload {
        /// Display name
        public let name: String
        /// Whether a user is allowed to publish audio/video tracks
        public let canPublish: Bool?
        /// User defined payload to store for the participant
        public let metadata: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter name: Display name
        /// - Parameter canPublish: Whether a user is allowed to publish audio/video tracks
        /// - Parameter metadata: User defined payload to store for the participant
        ///
        public init(name: String, canPublish: Bool? = nil, metadata: String? = nil) {
            self.name = name
            self.canPublish = canPublish
            self.metadata = metadata
        }
    }
}

extension Shared.RoomUserPayload: Codable {
    enum CodingKeys: String, CodingKey {
        case name
        case canPublish
        case metadata
    }
}

