// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct CreateRoomResponse {
        /// The ID of the room
        public let id: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter id: The ID of the room
        ///
        public init(id: String? = nil) {
            self.id = id
        }
    }
}

extension Shared.CreateRoomResponse: Codable {
    enum CodingKeys: String, CodingKey {
        case id
    }
}

