// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Inline multistream target object. Will automatically
    /// create the target resource to be used by the created
    /// stream.
    /// 
    public struct TargetAddPayloadSpec {
        /// Livepeer-compatible multistream target URL (RTMP(S) or SRT)
        public let url: String
        public let name: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter url: Livepeer-compatible multistream target URL (RTMP(S) or SRT)
        ///
        public init(url: String, name: String? = nil) {
            self.url = url
            self.name = name
        }
    }
}

extension Shared.TargetAddPayloadSpec: Codable {
    enum CodingKeys: String, CodingKey {
        case url
        case name
    }
}

