// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Output of the export data task
    public struct TaskExportData {
        public let ipfs: Shared.TaskSchemasIpfs?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(ipfs: Shared.TaskSchemasIpfs? = nil) {
            self.ipfs = ipfs
        }
    }
}

extension Shared.TaskExportData: Codable {
    enum CodingKeys: String, CodingKey {
        case ipfs
    }
}

