// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct TaskTranscode {
        public let asset: [String: AnyValue]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(asset: [String: AnyValue]? = nil) {
            self.asset = asset
        }
    }
}

extension Shared.TaskTranscode: Codable {
    enum CodingKeys: String, CodingKey {
        case asset
    }
}

