// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Type of the task
    public enum TaskType: String, Codable, APIValue {
        case upload = "upload"
        case `import` = "import"
        case export = "export"
        case exportData = "export-data"
        case transcode = "transcode"
        case transcodeFile = "transcode-file"
        case clip = "clip"
    }
}
