// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct TaskIpfs {
        /// IPFS CID of the exported video file
        public let videoFileCid: String
        /// IPFS CID of the default metadata exported for the video
        public let nftMetadataCid: String?
        /// URL to access metadata file via HTTP through an IPFS
        /// gateway
        /// 
        public let nftMetadataGatewayUrl: String?
        /// URL for the metadata file with the IPFS protocol
        public let nftMetadataUrl: String?
        /// URL to access file via HTTP through an IPFS gateway
        public let videoFileGatewayUrl: String?
        /// URL for the file with the IPFS protocol
        public let videoFileUrl: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter videoFileCid: IPFS CID of the exported video file
        /// - Parameter nftMetadataCid: IPFS CID of the default metadata exported for the video
        /// - Parameter nftMetadataGatewayUrl: URL to access metadata file via HTTP through an IPFS
        /// gateway
        /// 
        /// - Parameter nftMetadataUrl: URL for the metadata file with the IPFS protocol
        /// - Parameter videoFileGatewayUrl: URL to access file via HTTP through an IPFS gateway
        /// - Parameter videoFileUrl: URL for the file with the IPFS protocol
        ///
        public init(videoFileCid: String, nftMetadataCid: String? = nil, nftMetadataGatewayUrl: String? = nil, nftMetadataUrl: String? = nil, videoFileGatewayUrl: String? = nil, videoFileUrl: String? = nil) {
            self.videoFileCid = videoFileCid
            self.nftMetadataCid = nftMetadataCid
            self.nftMetadataGatewayUrl = nftMetadataGatewayUrl
            self.nftMetadataUrl = nftMetadataUrl
            self.videoFileGatewayUrl = videoFileGatewayUrl
            self.videoFileUrl = videoFileUrl
        }
    }
}

extension Shared.TaskIpfs: Codable {
    enum CodingKeys: String, CodingKey {
        case videoFileCid
        case nftMetadataCid
        case nftMetadataGatewayUrl
        case nftMetadataUrl
        case videoFileGatewayUrl
        case videoFileUrl
    }
}

