// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// HLS output format
    public struct TaskHls {
        /// Path for the HLS output
        public let path: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter path: Path for the HLS output
        ///
        public init(path: String? = nil) {
            self.path = path
        }
    }
}

extension Shared.TaskHls: Codable {
    enum CodingKeys: String, CodingKey {
        case path
    }
}

