// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Three {
        public let type: Shared.AssetSchemasSource3Type
        public let encryption: Shared.EncryptionOutput?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(type: Shared.AssetSchemasSource3Type, encryption: Shared.EncryptionOutput? = nil) {
            self.type = type
            self.encryption = encryption
        }
    }
}

extension Shared.Three: Codable {
    enum CodingKeys: String, CodingKey {
        case type
        case encryption
    }
}

