// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Three {
        public let type: Shared.AssetSchemasSource3Type
        /// ID of the asset from which this asset was created
        public let assetId: String?
        public let encryption: Shared.Encryption?
        /// Playback ID of the asset or stream from which this asset was created
        public let playbackId: String?
        /// ID of the requester from which this asset was created
        public let requesterId: String?
        /// ID of the session from which this asset was created
        public let sessionId: String?
        /// ID of the asset or stream from which this asset was created
        public let sourceId: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter assetId: ID of the asset from which this asset was created
        /// - Parameter playbackId: Playback ID of the asset or stream from which this asset was created
        /// - Parameter requesterId: ID of the requester from which this asset was created
        /// - Parameter sessionId: ID of the session from which this asset was created
        /// - Parameter sourceId: ID of the asset or stream from which this asset was created
        ///
        public init(type: Shared.AssetSchemasSource3Type, assetId: String? = nil, encryption: Shared.Encryption? = nil, playbackId: String? = nil, requesterId: String? = nil, sessionId: String? = nil, sourceId: String? = nil) {
            self.type = type
            self.assetId = assetId
            self.encryption = encryption
            self.playbackId = playbackId
            self.requesterId = requesterId
            self.sessionId = sessionId
            self.sourceId = sourceId
        }
    }
}

extension Shared.Three: Codable {
    enum CodingKeys: String, CodingKey {
        case type
        case assetId
        case encryption
        case playbackId
        case requesterId
        case sessionId
        case sourceId
    }
}

