// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// S3-like storage input video
    public struct TranscodePayload2 {
        /// Bucket with input file
        public let bucket: String
        /// Credentials for the private input video storage
        public let credentials: Shared.Credentials
        /// Service endpoint URL (AWS S3 endpoint list: https://docs.aws.amazon.com/general/latest/gr/s3.html, GCP S3 endpoint: https://storage.googleapis.com, Storj: https://gateway.storjshare.io)
        public let endpoint: String
        /// Path to the input file inside the bucket
        public let path: String
        /// Type of service. This is optional and defaults to `url` if
        /// ŚURL field is provided.
        /// 
        public let type: Shared.TranscodePayloadType

        /// Creates an object with the specified parameters
        ///
        /// - Parameter bucket: Bucket with input file
        /// - Parameter credentials: Credentials for the private input video storage
        /// - Parameter endpoint: Service endpoint URL (AWS S3 endpoint list: https://docs.aws.amazon.com/general/latest/gr/s3.html, GCP S3 endpoint: https://storage.googleapis.com, Storj: https://gateway.storjshare.io)
        /// - Parameter path: Path to the input file inside the bucket
        /// - Parameter type: Type of service. This is optional and defaults to `url` if
        /// ŚURL field is provided.
        /// 
        ///
        public init(bucket: String, credentials: Shared.Credentials, endpoint: String, path: String, type: Shared.TranscodePayloadType) {
            self.bucket = bucket
            self.credentials = credentials
            self.endpoint = endpoint
            self.path = path
            self.type = type
        }
    }
}

extension Shared.TranscodePayload2: Codable {
    enum CodingKeys: String, CodingKey {
        case bucket
        case credentials
        case endpoint
        case path
        case type
    }
}

