// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum TranscodeProfileEncoder: String, Codable, APIValue {
        case h264 = "h264"
        case hevc = "hevc"
        case vp8 = "vp8"
        case vp9 = "vp9"
    }
}
