// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Type of service used for output files
    public enum TranscodePayloadSchemasType: String, Codable, APIValue {
        case s3 = "s3"
    }
}
