// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    public enum TranscodeProfileProfile: String, Codable, APIValue {
        case h264Baseline = "H264Baseline"
        case h264Main = "H264Main"
        case h264High = "H264High"
        case h264ConstrainedHigh = "H264ConstrainedHigh"
    }
}
