// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Parameters for the transcode task
    public struct Transcode {
        /// LMPS ffmpeg profile
        public let profile: Shared.FfmpegProfile?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter profile: LMPS ffmpeg profile
        ///
        public init(profile: Shared.FfmpegProfile? = nil) {
            self.profile = profile
        }
    }
}

extension Shared.Transcode: Codable {
    enum CodingKeys: String, CodingKey {
        case profile
    }
}

