// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Type of service. This is optional and defaults to `url` if
    /// ŚURL field is provided.
    /// 
    public enum TranscodePayloadType: String, Codable, APIValue {
        case s3 = "s3"
    }
}
