// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Two {
        /// ID of the session from which this asset was created
        public let sessionId: String
        public let type: Shared.AssetSchemasSourceType

        /// Creates an object with the specified parameters
        ///
        /// - Parameter sessionId: ID of the session from which this asset was created
        ///
        public init(sessionId: String, type: Shared.AssetSchemasSourceType) {
            self.sessionId = sessionId
            self.type = type
        }
    }
}

extension Shared.Two: Codable {
    enum CodingKeys: String, CodingKey {
        case sessionId
        case type
    }
}

