// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Parameters for the upload task
    public struct Upload {
        /// Decides if the output video should include C2PA signature
        public let c2pa: Bool?
        public let encryption: Shared.Encryption?
        /// URL of the asset to "upload"
        public let url: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter c2pa: Decides if the output video should include C2PA signature
        /// - Parameter url: URL of the asset to "upload"
        ///
        public init(c2pa: Bool? = nil, encryption: Shared.Encryption? = nil, url: String? = nil) {
            self.c2pa = c2pa
            self.encryption = encryption
            self.url = url
        }
    }
}

extension Shared.Upload: Codable {
    enum CodingKeys: String, CodingKey {
        case c2pa
        case encryption
        case url
    }
}

