// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Shared.Encryption: Serializable {
    func serialize(with format: SerializableFormat) throws -> String {
        return ""
    }
}
