// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Shared.Security: SecurityParameterProviding {
    func securityParameters() -> [SecurityParameter] {
        switch self {
        case .apiKey(let value):
            return [.apiKey(name: "Authorization", value: value)]
        }
    }
}
